# Generated by Django 2.2.5 on 2019-09-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='área',
            new_name='nome',
        ),
    ]
